const API_URL = 'https://countriesnow.space/api/v0.1';
const API_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InVzZXJfZW1haWwiOiJoYW1tYWFnYXphcm9rQGdtYWlsLmNvbSIsImFwaV90b2tlbiI6IllZR01zNW9zenctVzd6amJZYm9ldkdVVHRERU1YZjA0ZldvbmpkR1paMVdJR193VVJUVjdaNThXS3JOajFweEY0NVkifSwiZXhwIjoxNjYyMjE3NzMxfQ.UkQt_kZn3XuTY7Bwan_6JIQUJgyRJtdxLI-BxtBRy_o';

export { API_URL, API_TOKEN };
